# Generated by Django 4.1.1 on 2022-11-22 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_variationvalue_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationvalue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
