# Generated by Django 4.1.6 on 2023-02-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_is_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_stock',
            field=models.IntegerField(default=0),
        ),
    ]
